services:
  bot:
    # Using the public image
    image: ghcr.io/raidensakura/modmail:stable
    # Building the image locally
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
      - action: sync+restart
        path: ./
        target: /app
        ignore:
          - .venv/
    container_name: modmail
    restart: always
    environment:
      - CONNECTION_URI=mongodb://mongo
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: modmail-db
    restart: always
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: