name: Lint python

on:
  push:
    branches:
      - stable
      - develop
  pull_request:

jobs:
  code-style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    name: Python ${{ matrix.python-version }} on ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run ruff linter
        run: uv run ruff check --config pyproject.toml
        continue-on-error: true
      - name: Run black linter
        run: |
          uv run black . --diff --check --config pyproject.toml
