name: Load test

on:
  push:
    branches:
      - develop

jobs:
  load-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false

    name: Load Modmail - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync

      - name: Run script loadcheck.py
        run: |
          poetry run python .github/workflows/scripts/loadcheck.py
        env:
          TOKEN: ${{ secrets.DISCORD_TEST_BOT }}
          CONNECTION_URI: ${{ secrets.CONNECTION_URI }}
          LOG_URL: https://example.com
          GUILD_ID: "1100011945207271494"
          OWNERS: "243316261264556032,505386507440488458"
          LOG_LEVEL: DEBUG

      - name: Save Modmail output as Artifact
        if: always() # still run if prev step failed
        uses: actions/upload-artifact@v4
        with:
          name: "Modmail log - Python ${{ matrix.python-version }}"
          path: modmail.log
